### ISSUE TITLE
Second live reload crahes the app when trailpack-repl and trailpack-webpack are enabled.

### ISSUE THREAD

**Issue by zuker** [trailsjs/trailpack-repl#24]
config/main.js

```
{
...
  packs: [
    require('trailpack-repl'),
    require('trailpack-webpack'),
    require('trailpack-autoreload')
  ]
...
}
```

When **second** autoreload triggered:

```
debug: Unloading trailpack repl
trailpack-repl/index.js:78
    this.server.removeAllListeners('exit')
               ^

TypeError: Cannot read property 'removeAllListeners' of undefined
    at REPL.unload (trailpack-repl/index.js:78:16)
...
```

**Comment by tjwebb** [comment]
Strange, I didn't find this in testing. Which version of node are you running?

**Comment by tjwebb** [comment]
This may have been broken at one point, but `this.server` should not be undefined. See https://github.com/trailsjs/trailpack-repl/commit/75450edf821d2b30ce3b3a0955cdb91ed8d530ee

**Comment by zuker** [comment]
@tjwebb just tried with:

```
"trailpack-repl": "^1.0.0-beta-4",
"trailpack-router": "^1.0.0-beta-4",
"trailpack-webpack": "https://github.com/trailsjs/trailpack-webpack/tarball/master"
"trailpack-autoreload": "^1.0.2",
```

Everything works perfectly!
Tanks!

**Comment by tjwebb** [comment]
ok, so the repl version was just old?

**Comment by zuker** [comment]
Sorry, can't clearly confirm that it was version issue, but it seems yes.

**Comment by jaumard** [comment]
Look fixed, closing this, feel free to reopen if it's not :) thanks
